af_unix: Pass struct sock to unix_autobind().
We do not use struct socket in unix_autobind() and pass struct sock to
unix_bind_bsd() and unix_bind_abstract().  Let's pass it to unix_autobind()
as well.

Also, this patch fixes these errors by checkpatch.pl.

  ERROR: do not use assignment in if condition
  #1795: FILE: net/unix/af_unix.c:1795:
  +	if (test_bit(SOCK_PASSCRED, &sock->flags) && !u->addr

  CHECK: Logical continuations should be on the previous line
  #1796: FILE: net/unix/af_unix.c:1796:
  +	if (test_bit(SOCK_PASSCRED, &sock->flags) && !u->addr
  +	    && (err = unix_autobind(sock)) != 0)

Signed-off-by: Kuniyuki Iwashima <kuniyu@amazon.co.jp>
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
(cherry picked from commit f988cc3fe6775b2d1b078450c2509274faca691a)
(cherry picked from commit a51ebd6ffcf893a4e1c8b0a23ff822e713940bc2)
(cherry picked from commit fa3d50e0449d58428ee971a662d28036729f0b60)
(cherry picked from commit 9fd0aaa6d8d8b53416c950e3150b0e3cec480f7f)
(cherry picked from commit 7534acdab4ff7fad1e2a3d519d453760fa735c90)
(cherry picked from commit 6f0f9d56ac0f8bd0d26fd9ead822c19ad5bf977b)